openapi: 3.1.0
info:
  title: Juno Memory API
  description: API for querying Junk Kouture knowledge base using vector embeddings
  version: 1.0.0
servers:
  - url: https://juno-backend-7lj5.onrender.com
paths:
  /query:
    post:
      operationId: queryKnowledgeBase
      summary: Query the Juno knowledge base
      description: Searches the embedded knowledge base and returns AI-generated answers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The user's question or search query
                  example: "What are the rules for Junk Kouture competition?"
              required:
                - query
      responses:
        '200':
          description: AI-generated answer based on knowledge base content
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: AI-generated answer based on knowledge base content
                    example: "According to the competition handbook, participants must..."
                  sources:
                    type: array
                    description: List of sources used to generate the answer
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Source name
                        similarity:
                          type: number
                          description: Similarity score
                        rank:
                          type: integer
                          description: Source ranking
                        image_url:
                          type: string
                          description: URL of the image associated with the source, if available
                        description:
                          type: string
                          description: Brief description of the image
                  confidence:
                    type: string
                    description: Confidence level of the answer
                    enum: [high, medium, low]
                  context_used:
                    type: integer
                    description: Number of content chunks used
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string

  /get-content:
    get:
      operationId: getNotionContent
      summary: Get specific Notion page content
      description: Retrieves content from a specific Notion page by title
      parameters:
        - name: page_name
          in: query
          required: true
          description: Title of the Notion page to retrieve
          schema:
            type: string
            example: "Competition Rules"
      responses:
        '200':
          description: Notion page content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Raw content from the Notion page
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string

  /ping:
    get:
      operationId: pingHealthCheck
      summary: Health check endpoint
      description: Simple endpoint to check if the API is running
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"

  /save_chat:
    post:
      operationId: saveChatTranscript
      summary: Save a chat or interview as a markdown transcript and upload to Notion and Supabase
      description: Saves a chat conversation to a markdown file and stores it in Notion and/or Supabase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chat_id:
                  type: string
                  description: Unique identifier for the chat, used as filename
                messages:
                  type: array
                  description: List of chat messages
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum: [user, assistant]
                      content:
                        type: string
                    required:
                      - role
                      - content
                destination:
                  type: string
                  enum: [notion, supabase, both]
                  default: notion
                notion_page_name:
                  type: string
                  description: The Notion page to upload the transcript to
              required:
                - chat_id
                - messages
                - notion_page_name
      responses:
        '200':
          description: Chat successfully saved and uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  saved_as:
                    type: string
                    description: Name of the saved markdown file
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
  /upload_file_from_gpt:
    post:
      operationId: uploadTextFileToNotion
      summary: Upload a text-based file and attach it to a Notion page
      description: Accepts text-based file content via JSON and uploads it to a Notion page. Supports .txt, .md, .yaml, .log, and .json files.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: Name of the file to upload (e.g., "notes.md")
                file_content:
                  type: string
                  description: The full plain-text content of the file
                notion_page_name:
                  type: string
                  description: Title of the Notion page to attach the file to
              required:
                - filename
                - file_content
                - notion_page_name
      responses:
        '200':
          description: File successfully attached to Notion
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  filename:
                    type: string
                    description: The final uploaded filename
                  notion_page:
                    type: string
                    description: The Notion page the file was attached to
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
  /search-images:
    get:
      operationId: searchImages
      summary: Search images in the knowledge base
      description: Returns images that match a search query based on caption or context
      parameters:
        - name: query
          in: query
          required: true
          description: Search query for images
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: Number of images to return
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: Matching images found
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        source:
                          type: string
                        url:
                          type: string
                        filename:
                          type: string
                        description:
                          type: string
                        searchable_text:
                          type: string
                  total_found:
                    type: integer
                  query:
                    type: string
        '500':
          description: Internal server error
  /analyze-images:
    post:
      operationId: analyzeImages
      summary: Analyze images with a prompt using GPT-4 Vision
      description: Accepts a list of image URLs and a custom prompt for analysis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image_urls:
                  type: array
                  items:
                    type: string
                  description: List of image URLs to analyze
                prompt:
                  type: string
                  description: Prompt for GPT-4 Vision to analyze the images
      responses:
        '200':
          description: Image analysis results
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis:
                    type: string
                  images_analyzed:
                    type: integer
                  prompt_used:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /creative-with-images:
    post:
      operationId: generateCreativeConcept
      summary: Generate creative design ideas using reference images
      description: Uses reference images from the knowledge base to suggest creative design directions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                  description: Description of the creative task (e.g. "create a campaign poster")
                reference_images:
                  type: array
                  items:
                    type: string
                  description: Optional list of image URLs to use as inspiration
                additional_context:
                  type: string
                  description: Extra context to guide the creative output
      responses:
        '200':
          description: Creative concept generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  creative_concept:
                    type: string
                  reference_images_used:
                    type: array
                    items:
                      type: string
                  task:
                    type: string
                  images_analyzed:
                    type: integer
        '500':
          description: Internal server error
components:
  schemas: {}
security: []