openapi: 3.1.0
info:
  title: Juno Memory API
  version: 1.0.0
servers:
  - url: https://juno-backend-gbya.onrender.com
paths:
  /query:
    post:
      operationId: queryKnowledgeBase
      summary: Query the Juno knowledge base
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Matching content from the knowledge base
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      type: string

components: {}
security: []